### ISSUE TITLE
Possible code indentation problem in unit testing

### ISSUE THREAD

**Issue by avigan** [tomasstolker/pycrires#15]
I am not entirely sure, but I think there are some problems in your test functions. Let's take the example of `test_util_calib_fpet()`:

```python
def test_util_calib_fpet(self) -> None:
    if shutil.which("esorex") is None:
        with pytest.raises(RuntimeError) as error:
            self.pipeline.util_calib(calib_type="fpet", verbose=False)
        assert str(error.value) == self.esorex_error
    else:
        self.pipeline.util_calib(calib_type="fpet", verbose=False)
```

I think the indentation of `assert str(error.value) == self.esorex_error` is not correct. This statement should be within the scope of `with ...`, otherwise `error` is not defined. This is the case in all your test functions.

However, I am not 100% sure here, so maybe it's just me! ;-)

**Comment by tomasstolker** [comment]
Yes, I think you are right! I will fix it.

About the previous PR, should error that is raised with `if len(science_index) > 0` actually be `if len(science_index) == 0`?
